# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Machine Learning and Adaptive Intelligence module
author:
  name: Neil D. Lawrence
  email:
  twitter: lawrennd
description: >- # this means to ignore newlines until "baseurl:"
  This is the website of the Machine Learning and Adaptive Intelligence
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/mlai" # the subpath of your site, e.g. /blog
twitter_username:
github_username: mlatcl
colab: https://colab.research.google.com
nbviewer: https://nbviewer.jupyter.org

slidesdir: slides
reveal:
  width: 512
  height: 384
youtube:
  width: 512
  height: 384

collections:
  updates:
    output: true
  lectures:
    permalink: /lectures/:title:output_ext
    output: true
    sort_by: week
  special_topics:
    permalink: /special_topics/:title:output_ext
    output: true
    sort_by: label
  practicals:
    permalink: /practicals/:title:output_ext
    output: true
    sort_by: week

ghub:
  edit: true
  repository: mlai

analytics:
  google: 
    tracking_id: UA-184894912-1

future: true

# Build settings
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
- jekyll-paginate-v2
sass:
  sass_dir: _sass
# Pagination
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

remote_theme: mlatcl/jekyll-theme
twitter_svg: ./assets/images/social-tw.svg
facebook_svg: ./assets/images/social-fb.svg
instagram_svg: ./assets/images/social-in.svg
image_root: ./assets/images/
markdown: kramdown
twitter_username: mlatcl
github_username: mlatcl

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - slides/reveal.js/plugin/markdown/example
  - slides/reveal.js/plugin/markdown/example
  - slides/reveal.js-3.8.0/plugin/markdown/example
  - slides/reveal.js-3.8.0/test/
  - slides/reveal.js-3.8.0/css/theme/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
